apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: three-tier
  region: eu-west-2
  version: "1.31"

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    # This automatically adds the necessary IAM policies to be attached to the nodes
    iam:
      withAddonPolicies:
        imageBuilder: true
        albIngress: true
        cloudWatch: true
